[package]
name = "entity_core"
version = "0.0.4"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }
camino = { workspace = true }
thiserror = { workspace = true }
indexmap = { workspace = true }
